### ISSUE TITLE
某些有歌詞的debug有寫，但是真實output沒有出現歌詞

### ISSUE THREAD

**Issue by EdGithubImageACV** [MikiraSora/LyricDisplayerPlugin#1]

**Comment by MikiraSora** [comment]
提供一下谱面~

**Comment by EdGithubImageACV** [comment]
https://osu.ppy.sh/beatmapsets/52879#osu/163570
![image](https://user-images.githubusercontent.com/78646217/109256688-64d92f00-77ab-11eb-9126-069f7e28d3f6.png)

**Comment by EdGithubImageACV** [comment]
https://osu.ppy.sh/beatmapsets/92509#osu/255689
![image](https://user-images.githubusercontent.com/78646217/109257390-e7162300-77ac-11eb-8c46-c92ab99c483d.png)

**Comment by EdGithubImageACV** [comment]
https://osu.ppy.sh/beatmapsets/426542#osu/920987
![image](https://user-images.githubusercontent.com/78646217/109257570-4b38e700-77ad-11eb-8735-32fb75f8ae5b.png)

**Comment by EdGithubImageACV** [comment]
https://osu.ppy.sh/beatmapsets/300034#osu/784169
![image](https://user-images.githubusercontent.com/78646217/109258091-6b1cda80-77ae-11eb-9522-3211075fde33.png)

**Comment by MikiraSora** [comment]
你发的那些列表都是搜索歌词的结果， 看格式就知道大概信息了:
```
 [搜索标记] music_id:... artist:.... title:.... ([和谱面歌曲长度相差])
```
搜索标记我记得有三个, - 表示搜索到的歌词但长度不匹配(>1000ms) , * 表示搜索到且歌曲长度相似(<1000ms) , + 表示插件钦定这一份歌词并使用它。
因此你发的图有好几个都是搜索结果，长度都不比配的，因此插件无法采纳这些歌词。
有些可能有歌曲长度是相似的，但这份歌曲没有提供歌词的。

**Comment by EdGithubImageACV** [comment]
明白，謝謝幫助！

**Comment by EdGithubImageACV** [comment]
其實可以弄使用者選擇的嗎？如果可以的話非常感激！

**Comment by MikiraSora** [comment]
你是说可以用户可以直接对某个谱面配置指定的歌词文件？ 
目前是不可以，因为一般来说我都是为了全自动懒人而设计的。而且时间差相差太大，比如小妹妹唱歌唱到这一段，结果显示歌词就偏了好几段，观感太差。这就是我为什么钦定时间差在1秒以内就采用的原因。
如果真想要的话可能过几天等我工作能摸了就搞搞看吧?
不过估计我只能做出使用前，用户手动添加以下内容，才能强制钦定:
```
"曲名" "艺术家" "谱面歌曲长度" -> "来源id" "来源名称"
"Endless Story" "田村ゆかり" "189000" -> "1qw54es87qwe" "netease"
```

**Comment by EdGithubImageACV** [comment]
對就是這個。我相信你可以的，我可以等，不用趕。加油！
